sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-sound-image .
script:
  # the "yast-travis-cpp" script is included in the base yastdevel/cpp-tw image
  # see https://github.com/yast/docker-yast-cpp-tw/blob/master/yast-travis-cpp
  - docker run -it yast-sound-image yast-travis-cpp
  - docker run -it yast-sound-image bash -c "rake check:syntax && rake check:pot"
